
# [Имя таблицы] должно соответствовать названию соответствующего параметра в интерфейсной плате
# name - текстовое название параметра (Используется в меню)
# possible_values - список возможных значений параметра
# default - значение по умолчанию
# current - актуальное текущее значение параметра. Если не указано или некорректно, то используется значение по умолчанию

[groupnumber]
name = "Номер в группе"
possible_values = [
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
]
default = "0"
current = "6"

[soundvolume]
name = "Громкость звука"
possible_values = ["0%", "25%", "50%", "75%", "100%"]
default = "50%"
current = "50%"

[musicvolume]
name = "Громкость музыки"
possible_values = ["0%", "25%", "50%", "75%", "100%"]
default = "0%"
current = "100%"

[loadcapacity]
name = "Грузоподъемность"
possible_values = [
    "СКРЫТО",
    "240кг 3чел.",
    "320кг 4чел.",
    "400кг 5чел.",
    "450кг 6чел.",
    "525кг 7чел.",
    "630кг 8чел.",
    "800кг 10чел.",
    "800кг 11чел.",
    "1000кг 13чел.",
    "1150кг 15чел.",
    "1275кг 16чел.",
    "1275кг 17чел.",
    "1425кг 18чел.",
    "1600кг 20чел.",
    "1600кг 21чел.",
]
default = "СКРЫТО"
current = "240кг 3чел."
