# [table name] должно соответствовать названию соответствующего параметра в ПО для интерфейсной платы
# name - текстовое название параметра (используется в TUI меню)
# possible_values - список возможных значений параметра
# default - значение по умолчанию (одно из possible_values)
# current - актуальное текущее значение параметра (одно из possible_values). Если не указано или некорректно, то используется значение по умолчанию

[device]
name = "Имя порта"
possible_values = ["/dev/ttyS4"]
default = "/dev/ttyS4"
current = "/dev/ttyS4"

[baudrate]
name = "Скорость передачи данных"
possible_values = ["9600", "38400", "115200"]
default = "115200"
current = "115200"
