[package]
name = "logger"
version = "0.1.0"
edition = "2024"
authors.workspace = true

[dependencies]
chrono = "0.4"
protocol_lib = { path = "../protocol_lib" }
config_lib = { path = "../config_lib" }
log = { workspace = true }
env_logger = { workspace = true }
serialport = { workspace = true }
signal-hook = "0.3"