[package]
name = "config_lib"
version = "0.1.0"
edition = "2024"
authors.workspace = true

[dependencies]
rand = "0.9.1"
toml_edit = "0.23.2"
log = { workspace = true }
env_logger = { workspace = true }
